
#FROM eclipse-temurin:21-jdk

#RUN useradd -m judge
#WORKDIR /workspace
#RUN chown -R judge:judge /workspace

#USER judge



FROM eclipse-temurin:21-jdk

RUN useradd -m runner
WORKDIR /workspace
USER runner
