#FROM python:3.13-slim

#RUN useradd -m judge
#WORKDIR /workspace
#RUN chown -R judge:judge /workspace

#USER judge


FROM python:3.12-slim

RUN useradd -m runner
USER runner

WORKDIR /workspace

CMD ["sleep", "infinity"]
