# Dockerfile.server
FROM oven/bun:1 AS base

WORKDIR /app

# Install deps for the server (root package.json)
COPY package.json bun.lockb* ./
RUN bun install


COPY public ./public

# Copy server source
COPY server ./server

# Build server (TS -> JS bundle)
RUN bun build ./server/index.ts --outdir ./dist --target bun

EXPOSE 4000

# Run built server
CMD ["bun", "run", "dist/index.js"]
